---
check_all_level1_locations: true
check_all_level2_locations: true
check_all_level3_locations: true
check_cds: true
check_exons: true
check_identical_isoforms: true
check_l1_linked_to_l2: true
check_l2_linked_to_l3: true
check_sequential: true
check_utrs: true
clean_attributes_from_template: 0
create_l3_for_l2_orphan: true
debug: 0
force_gff_input_version: 0
gff_output_version: 3
gtf_output_version: relax
locus_tag:
  - locus_tag
  - gene_id
log: true
merge_loci: 0
output_format: gff
prefix_new_id: agat
progress_bar: true
remove_orphan_l1: true
tabix: true
throw_fasta: 0
verbose: 1
