- name: Install Miniconda3 and create Conda environment
  hosts: ubuntu@207.211.190.108 # Host to run the playbook on
  become: yes # Run tasks as root
  gather_facts: no # Don't gather facts about the remote system
  vars:
    ansible_private_key_file: "~/keys/ssh-key-2024-04-08.key"

  tasks:
    - name: Download Miniconda3 installer
      get_url:
        url: "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-aarch64.sh"
        dest: "~/tmp/Miniconda3-latest-Linux-x86_64.sh"
        mode: 0755

    - name: Install Miniconda3
      command: "~/tmp/Miniconda3-latest-Linux-x86_64.sh -b -p ~/miniconda3"
      args:
        creates: "~/miniconda3"

    - name: Create Conda environment from environment.yml
      command: "~/miniconda3/bin/conda env create -f /path/to/environment.yml"

